
services:
  flask:
    #build: 
      #context: ./flask_app
      #dockerfile: Dockerfile
    image: rangulo1972/scale-flask
    environment:
      - FLASK_ENV=development
    expose:
      - 5000
    networks:
      - app-network2
  nginx:
    #build:
      #context: ./nginx
      #dockerfile: Dockerfile
    image: rangulo1972/scale-nginx
    ports:
      - 8080:80
    depends_on:
      - flask
    networks:
      - app-network2

networks:
  app-network2:
    driver: bridge
    